var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/reports/neraca/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__00k8obu._.js")
R.c("server/chunks/ssr/node_modules_09r9c10._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0ldvg1r.js")
R.c("server/chunks/ssr/[root-of-the-server]__05a5hj0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1au0nys._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0buje5o._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_reports_neraca_page_actions_0y8sayz.js")
R.m(80552)
module.exports=R.m(80552).exports
